### ISSUE TITLE
Doc links are 404

### ISSUE THREAD

**Issue by lexoyo** [stackbithq/unibit#19]
On [the documentation](https://docs.stackbit.com/unibit/) all the links lead to a 404

**Comment by lgs** [comment]
It's more then a month now, we get **http error 404 "page not found"**  on every page under [unibit doc](https://www.stackbit.com/docs/docs/unibit/installation/)

**Comment by ramonsnir** [comment]
@lgs You can find the docs here: https://www.stackbit.com/docs/unibit/ .
