### ISSUE TITLE
unibit is dead？

### ISSUE THREAD

**Issue by hxgdzyuyi** [stackbithq/unibit#38]

**Comment by hxgdzyuyi** [comment]
@stackbit-admin

**Comment by hxgdzyuyi** [comment]
@smnh smnh

**Comment by smnh** [comment]
Hey @hxgdzyuyi,

Yes, Stackbit has stopped further development and support of Unibit.
Instead, Stackbit allows importing sites written on any web-framework to edit their content visually.
